### ISSUE TITLE
Negative numbers?

### ISSUE THREAD

**Issue by srl295** [caridy/intl-plural-rules-spec#2]
I noticed that the spec here takes the [absolute value](https://github.com/caridy/intl-plural-rules-spec/blob/master/spec/pluralrules.html#L237) of any negative number. This seems to be under specified in CLDR at present, [CldrBug:8988](http://unicode.org/cldr/trac/ticket/8988) aims to address that.

I was curious what the reasoning was.

**Comment by caridy** [comment]
I wasn't sure, so I went with a safe bet. I could not find any reference or indication about that, but by looking into the produced function, I noticed that the algo seems to rely on an absolute value by assuming a numeric value in the first character, here is an example:

``` js
function (n, ord) {
    var s = String(n).split("."),
        v0 = !s[1],
        t0 = Number(s[0]) == n,
        n10 = t0 && s[0].slice(-1),
        n100 = t0 && s[0].slice(-2);
    if (ord) {
        return n10 == 1 && n100 != 11 ? "one" : n10 == 2 && n100 != 12 ? "two" : n10 == 3 && n100 != 13 ? "few" : "other";
    }
    return n == 1 && v0 ? "one" : "other"
}
```

**Comment by caridy** [comment]
This is now solved by calling `abs(_n_)` before trying to determine the shape of the number.
