### ISSUE TITLE
Spec refers to 'style' just once, in resolvedOptions(). Remove?

### ISSUE THREAD

**Issue by littledan** [caridy/intl-plural-rules-spec#27]
Was this inclusion mistaken? I can't figure out what it's supposed to refer to. cc @zbraniecki

**Comment by caridy** [comment]
IIRC, we want to use `style` instead of `type` to align with numberformat, it is just the style of the output not the type of the input value, which was the reasoning behind this change, but I guess we never complete it. A PR will be welcome.

**Comment by zbraniecki** [comment]
Umm, wait, for `cardinal` vs `ordinal`? I think it's a different type of the value, no?

In SM implementation I use `type` only. I'm ok switching it to `style` if @littledan and @caridy prefer, but it seems like we're talking about the type of a variable, not just style of the output.

**Comment by littledan** [comment]
I have no preference. To me, both `style` and `type` seem like words that are rather devoid of meaning. FWIW Intl.Segmenter used to have an option called `type` that I renamed to `granularity`. I can't think of a similarly more meaningful word here that captures the difference between them ("numbering"?).
