### ISSUE TITLE
Stage 4

### ISSUE THREAD

**Issue by zbraniecki** [caridy/intl-plural-rules-spec#35]
It seems like we should be ready to request stage 4:
 - SpiderMonkey impl is in: https://bugzilla.mozilla.org/show_bug.cgi?id=1270146
 - V8 impl is in: https://chromium-review.googlesource.com/c/v8/v8/+/562298

@caridy I assume it's on you as a champion of the proposal?

**Comment by zbraniecki** [comment]
We reached Stage 4 as of today!

**Comment by mathiasbynens** [comment]
Don’t forget to mark the proposal as such: #38.
