### ISSUE TITLE
Bound functions?

### ISSUE THREAD

**Issue by littledan** [caridy/intl-plural-rules-spec#6]
I noticed that https://rawgit.com/caridy/intl-plural-rules-spec/master/index.html#sec-Intl.PluralRules.prototype.select created a bound function. I think we were discussing, maybe new APIs should not use bound functions, due to the performance issues that they cause. What would you think about making this an ordinary method?

**Comment by caridy** [comment]
correct, I will remove the bound function for all new APIs.

**Comment by caridy** [comment]
removed.
